### One word at a time

In [2]:
import pandas as pd

text = ['cat', 'dog', 'fish', 'bird', 'cat', 'dog']

data = pd.get_dummies(text)

print(data)
print('-'*30)
print(data.keys())

   bird  cat  dog  fish
0     0    1    0     0
1     0    0    1     0
2     0    0    0     1
3     1    0    0     0
4     0    1    0     0
5     0    0    1     0
------------------------------
Index(['bird', 'cat', 'dog', 'fish'], dtype='object')


### Whole sentence at a time

In [4]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

text = ['i love dogs', 'i dont mind cats', 'turtles are alright']

text = np.reshape(text,(-1,1))

encoder = OneHotEncoder()
encoder.fit(text)

one_hot = encoder.transform(text)

print(one_hot.toarray())
print([i[3:] for i in encoder.get_feature_names_out()])

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
['i dont mind cats', 'i love dogs', 'turtles are alright']


### Tokenized sentence

In [9]:
from sklearn.preprocessing import OneHotEncoder

text = [['this', 'is', 'bad'], ['but', 'its', 'fine']]

encoder = OneHotEncoder()
encoder.fit(text)

one_hot = encoder.transform(text)

print(one_hot.toarray())
print('-'*30)
print([i[3:] for i in encoder.get_feature_names_out()])

[[0. 1. 1. 0. 1. 0.]
 [1. 0. 0. 1. 0. 1.]]
------------------------------
['but', 'this', 'is', 'its', 'bad', 'fine']


In [11]:
pd.DataFrame(one_hot.toarray(), columns= [i[3:] for i in encoder.get_feature_names_out()])

but  this   is  its  bad  fine
0  0.0   1.0  1.0  0.0  1.0   0.0
1  1.0   0.0  0.0  1.0  0.0   1.0